openapi: '3.0.2'
info:
  title: 'Demo v1.0.0'
  version: '1.0.0'
  description: !import_string ./description.md
paths:
  /article: !include ./api/article.yaml
  /articles: !include ./api/articles.yaml
